version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
  migrations:
    depends_on:
      - postgres
    links:
      - postgres
    build:
      context: ./
      dockerfile: Dockerfile_migrations
  car_api:
    expose: [ 8080 ]
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - postgres
    links:
      - postgres
    working_dir: /root/car_api
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile_back
    volumes:
      - ./:/root/car_api

volumes:
  db:
