FROM rust:1.67 as builder

WORKDIR /root/car_api

COPY ./car_api .

RUN cargo install --path .

FROM debian

RUN apt-get update

COPY --from=builder /usr/local/cargo/bin/car_api /usr/local/bin/car_api

CMD ["car_api"]